// fix_yelp.cjs — sanitizes yelpReviews.json and writes a clean TypeScript module
// Run: node scripts/fix_yelp.cjs
const fs = require('fs')
const path = require('path')

const input  = path.join(__dirname, '../src/data/yelpReviews.json')
const output = path.join(__dirname, '../src/data/yelpReviews.ts')

const raw = fs.readFileSync(input, 'utf8')

// ── Extract strings one by one, skipping malformed entries ───────────────────
const reviews = []
let pos = 0

while (pos < raw.length) {
  // Find the opening quote of the next string value
  const start = raw.indexOf('"', pos)
  if (start === -1) break

  // Walk forward to find the closing quote, honouring escape sequences
  let end = start + 1
  let valid = true

  while (end < raw.length) {
    const ch = raw[end]
    if (ch === '\\') {
      end += 2                 // skip backslash + next char
    } else if (ch === '"') {
      break                    // found the closing quote
    } else if (ch === '\n' || ch === '\r') {
      // Raw (unescaped) newline inside a JSON string → the bug
      valid = false
      break
    } else {
      end++
    }
  }

  if (!valid || end >= raw.length) {
    // Skip to the next newline and try again
    const skip = raw.indexOf('\n', start)
    pos = skip === -1 ? raw.length : skip + 1
    continue
  }

  // Extract the raw string content (between the quotes)
  let content = raw.slice(start + 1, end)

  // Unescape JSON escape sequences so we have plain text
  try {
    content = JSON.parse(`"${content}"`)
  } catch {
    // If that fails, do basic cleanup
    content = content
      .replace(/\\n/g, ' ')
      .replace(/\\t/g, ' ')
      .replace(/\\r/g, ' ')
  }

  // Remove any remaining ASCII control characters
  content = content.replace(/[\x00-\x1F\x7F]/g, ' ').trim()

  // Keep only reviews that are long enough to be useful
  if (content.length >= 80) {
    reviews.push(content)
  }

  pos = end + 1
}

console.log(`Extracted ${reviews.length} valid reviews from ${reviews.length + (raw.split('\n').length - reviews.length)} lines`)

// ── Write as a TypeScript module (no JSON.parse needed at runtime) ────────────
const ts = `// Yelp Open Dataset — Tours / Coffee & Tea / Agriculture / Nature Tours categories
// Source: yelp.com/dataset — academic use licence, Yelp Inc.
// Generated by scripts/fix_yelp.cjs from yelpReviews.json
// To regenerate: node scripts/fix_yelp.cjs

export const yelpReviews: string[] = [
${reviews.map(r => `  ${JSON.stringify(r)},`).join('\n')}
]
`

fs.writeFileSync(output, ts, 'utf8')
console.log(`Written ${reviews.length} reviews → ${output}`)
console.log('\nNext step: sampleData.ts will auto-import the new file.')
